In [12]:
# Start small and save your time.

In [13]:
# import necessary packages

import pandas as pd # for working with tables
pd.options.mode.chained_assignment = None  # default = 'warn'

import os # for finding file directory with os.getcwd()

# for calculations
import numpy as np 
import math

import matplotlib.pyplot as plt # for plotting

# for plotting histogram with percentages
from matplotlib.ticker import PercentFormatter
import matplotlib.ticker as mtick
from matplotlib.ticker import FormatStrFormatter

from PIL import Image # for converting plots to black-and-white
from IPython.display import HTML

from ipynb.fs.full.MyFunctions_00 import *

In [14]:
# remove "#" at the beginning

voids_parent = read_data_db('voids_parent_colors_new_' + '04-11-23') # timestamp())
walls_parent = read_data_db('walls_parent_colors_new_' + '04-11-23') # timestamp())

voids_parent.head()

read voids_parent_colors_new_04-11-23
read walls_parent_colors_new_04-11-23

,object_tag,num_obj,Pr,vflag,RA,DEC,PLATE,FIBERID,MJD,rabsmag_NSA,...,w2sigmpro,w2snr,w3mpro,w3sigmpro,w3snr,w4mpro,w4sigmpro,w4snr,W1-W2,W2-W3
0,75.0,24.0,0.933297,1,145.874464,-0.608775,266,138,51630,-20.979137,...,0.057,19.1,10.802,0.124,8.7,8.286,0.435,2.5,0.110,3.232
1,95.0,24.0,0.948802,1,146.222266,-0.375920,266,168,51630,-20.544321,...,0.029,37.9,9.610,0.044,24.9,8.194,0.273,4.0,0.163,3.465
2,121.0,23.0,0.987329,1,145.681110,-0.867233,266,207,51630,-21.178394,...,0.027,39.9,11.039,0.139,7.8,8.913,NaN,-0.5,0.034,1.967
3,127.0,22.0,0.998411,1,145.759730,-0.813891,266,216,51630,-20.736423,...,0.058,18.7,10.507,0.120,9.1,7.438,NaN,1.4,0.127,2.721
4,128.0,22.0,0.900567,1,145.708927,-0.747680,266,217,51630,-19.849358,...,0.041,26.8,12.431,NaN,0.0,8.759,NaN,-0.6,0.166,1.533

In [15]:
for col in voids_parent.columns:
    print(col)

object_tag
num_obj
Pr
vflag
RA
DEC
PLATE
FIBERID
MJD
rabsmag_NSA
Z
SFR
sSFR
BPTclass
HImass
u_r
g_r
u_r_err
g_r_err
cntr_01
dist_x
pang_x
ra_01
dec_01
ra
dec
w1mpro
w1sigmpro
w1snr
w2mpro
w2sigmpro
w2snr
w3mpro
w3sigmpro
w3snr
w4mpro
w4sigmpro
w4snr
W1-W2
W2-W3

In [16]:
desired_columns = [
    'object_tag',
    'Pr',
    'RA',
    'DEC',
    'PLATE',
    'FIBERID',
    'MJD'
]

In [17]:
voids_parent_cols = voids_parent[desired_columns]
walls_parent_cols = walls_parent[desired_columns]

voids_parent_cols.head()

   object_tag        Pr          RA       DEC  PLATE  FIBERID    MJD
0        75.0  0.933297  145.874464 -0.608775    266      138  51630
1        95.0  0.948802  146.222266 -0.375920    266      168  51630
2       121.0  0.987329  145.681110 -0.867233    266      207  51630
3       127.0  0.998411  145.759730 -0.813891    266      216  51630
4       128.0  0.900567  145.708927 -0.747680    266      217  51630

In [21]:
print(str(len(voids_parent_cols)))
new_voids_filt = voids_parent_cols.dropna(axis = 'index', 
                                          how = 'any', 
                                          subset = desired_columns)
print(str(len(new_voids_filt)))

print(str(len(walls_parent_cols)))
new_walls_filt = walls_parent_cols.dropna(axis = 'index', 
                                          how = 'any', 
                                          subset = desired_columns)
print(str(len(new_walls_filt)))

71261
71261
219255
219255

In [23]:
# rename old: new
new_voids_filt_named = new_voids_filt.rename(columns = {'object_tag' : 'NSAID', 'FIBERID':'FIBER'})
new_walls_filt_named = new_walls_filt.rename(columns = {'object_tag' : 'NSAID', 'FIBERID':'FIBER'})

new_voids_filt_named.head()

   NSAID        Pr          RA       DEC  PLATE  FIBER    MJD
0   75.0  0.933297  145.874464 -0.608775    266    138  51630
1   95.0  0.948802  146.222266 -0.375920    266    168  51630
2  121.0  0.987329  145.681110 -0.867233    266    207  51630
3  127.0  0.998411  145.759730 -0.813891    266    216  51630
4  128.0  0.900567  145.708927 -0.747680    266    217  51630

In [24]:
new_voids_filt_named.to_csv('Files/voids_for_optical_' + timestamp() + '.csv', index = False)

In [25]:
new_walls_filt_named.to_csv('Files/walls_for_optical_' + timestamp() + '.csv', index = False)